<a href="https://colab.research.google.com/github/19pa1a0227/AI-Lab-/blob/master/Experiment_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment:1 Numpy

## i) Different ways to create numpy arrays

### a) Using arange function

In [ ]:
# import NUMPY library as np
import numpy as np

In [ ]:
a=np.arange(1,10,2) #an array of odd nummbers created using numpy
print(a)

[1 3 5 7 9]


### b) Using general method 

In [ ]:
b= np.array([1,2,3])
b

array([1, 2, 3])

### c) Using numpy.zeroes

In [ ]:
c= np.zeros((2,2)) #creates an array of all zeros
c

array([[0., 0.],
       [0., 0.]])

### d) Using np.ones

In [ ]:
d= np.ones((3,3)) #creates an array of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### e) Using numpy.empty

In [ ]:
e=np.empty((2,2))  #creates an empyty array
e

array([[0., 0.],
       [0., 0.]])

### f) Using numpy.eye

In [ ]:
f=np.eye(3) #creates identity matrix
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### g) Using numpy.random.random

In [ ]:
g= np.random.random((2,3)) #creates an array of random values
g

array([[0.46895197, 0.96772276, 0.17604472],
       [0.85733834, 0.77143672, 0.99805161]])

 ## ii) Add, remove modify elements in a array

###  a) Adding elements to array

In [ ]:
s=np.array([1,2,3])
w=np.array([3,3,3])  #creates 2 arrays
s
w

array([3, 3, 3])

In [ ]:
a=np.append(S,W)  #joins two arrays
a

array([1, 2, 3, 3, 3, 3])

### b)Removing elements in an array

In [ ]:
t= np.delete(a,3) #removes the element in that index
t

array([1, 2, 3, 3, 3])

### c) Modifying elements in an array

In [ ]:
t[t>=3]=4
t

array([1, 2, 4, 4, 4])

## iii) Arithmetic operations on numpy array

### a)Addition

In [ ]:
a= np.array([[1,2,3],[1,2,3]])
b=np.array([[1,1,1],[2,2,2]])  #creates 2 2d arrays

In [ ]:
Sum =np.add(a,b) #adds the elements in the two arrays
Sum

array([[2, 3, 4],
       [3, 4, 5]])

### b) Subtraction

In [ ]:
Difference = np.subtract(a,b) 
Difference

array([[ 0,  1,  2],
       [-1,  0,  1]])

### c) Scalar Multiplication

In [ ]:
Scalar_multiplication= a**2
Scalar_multiplication

array([[1, 4, 9],
       [1, 4, 9]])

### d) Matrix Product


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,1],[2,2]])
mat_product = a@b
mat_product

array([[ 5,  5],
       [11, 11]])

## iv) Slicing and Iterating on numpy arrays

### a) Slicing on 1 dimensional array

In [ ]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(s[2]) #returns element in second index(scalar form)
print(s[2:4]) #returns the elements in 2nd & 3rd indices
print(s[2:3]) #returns element in second index(matrix form)

2
[2 3]
[2]


### b) Slicing 2d array

In [ ]:
s=np.arange(9).reshape(3,3)
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
print(s[1:2])  #prints second row
print(s[1:2,1:2]) #prints 2 nd element in 2nd and 3rd rows
print(s[2,]) #prints second row in scalar form 

[[3 4 5]]
[[4]]
[6 7 8]


### Negetive slicing

In [ ]:
h=np.arange(5)
h

array([0, 1, 2, 3, 4])

In [ ]:
print(h[-1:]) #prints last element in matrix form
print(h[-1]) #prints last element in scalar form

[4]
4


## Iteration

In [ ]:
c=np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
for i in c:
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [ ]:
for i in c.flat:
  print(i)

0
1
2
3
4
5
6
7
8


## 5) Matrix operations on numpy arrays

In [ ]:
a=np.array([[11,12],[13,14]])
c=np.array([[5,6],[7,8]])
print(np.add(a,c))
print(np.subtract(a,c))

[[16 18]
 [20 22]]
[[6 6]
 [6 6]]
